services:
  nominatim:
    build:
      context: .
      dockerfile: Dockerfile
    image: "nominatim:${NOMINATIM_VERSION}"
    container_name: nominatim
    command: ["tail", "-f", "/dev/null"]
    env_file:
      - .env
    expose:
      - ${NOMINATIM_PORT}
    depends_on:
      - db
  db:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    image: "nominatim-postgres:${DATABASE_VERSION}"
    container_name: nominatim-postgres
    restart: always
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_DATABASE: "${DATABASE_NAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    volumes:
      - nominatim-db-data:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
  starlette:
    build:
      context: ./starlette
      dockerfile: Dockerfile
    image: "starlette:${STARLETTE_VERSION}"
    container_name: nominatim-starlette
    command: "gunicorn -b ${STARLETTE_HOST}:${STARLETTE_PORT} -w 4 -k uvicorn.workers.UvicornWorker example:app"
    env_file:
      - .env
    volumes:
      - ./starlette:/srv/nominatim/nominatim-project
    ports:
      - "${STARLETTE_PORT}:${STARLETTE_PORT}"
    depends_on:
      - nominatim
volumes:
  nominatim-db-data:
