services:
  nominatim:
    build:
      context: .
      dockerfile: Dockerfile
    image: "nominatim:${NOMINATIM_VERSION}"
    container_name: nominatim
    env_file:
      - .env
    command: uvicorn example:app --host ${STARLETTE_HOST} --port ${STARLETTE_PORT}
    volumes:
      - .:/srv/nominatim/nominatim-project
    ports:
      - "${STARLETTE_PORT}:${STARLETTE_PORT}"
    depends_on:
      - db
  db:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    image: "nominatim-postgres:${DATABASE_VERSION}"
    container_name: nominatim-postgres
    restart: always
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_DATABASE: "${DATABASE_NAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    volumes:
      - nominatim-db-data:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
volumes:
  nominatim-db-data:
